### ISSUE TITLE
Errors encountered in `Why Do We Need Seed Data?`

### ISSUE THREAD

**Issue by viewsdevelop** [learn-co-curriculum/python-p3-working-with-seed-data#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204326?module_item_id=468321

### Concern

I was able to successfully create / retrieve the three test Game records, but only after a series of trial and error attempts.

---

Attempted to run `python debug.py` from `seed_db` directory

Error: `ModuleNotFoundError: No module named 'ipdb'`

Fix: `pip install ipdb`

---

Attempted to run `session.commit()` in `ipdb`

Error: `*** sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: games`

Attempt to Fix: `alembic revision --autogenerate -m "Add game model"`

---

Attempted to run `alembic revision --autogenerate -m "Add game model"`

Error: `ModuleNotFoundError: No module named 'importlib_resources'`

Fix: `pip install importlib_resources`

---

Attempted to run `alembic revision --autogenerate -m "Add game model"`

Error: `ModuleNotFoundError: No module named 'importlib_metadata`

Fix: `pip install importlib_metadata`

---

Attempted to run `alembic revision --autogenerate -m "Add game model"`

Error: `ERROR [alembic.util.messaging] Target database is not up to date. FAILED: Target database is not up to date.`

Fix: `alembic upgrade head`

### Suggested Changes

Refer to suggested fixes (Terminal commands) included above.

**Comment by professor-ben** [comment]
I believe the changes about to be pushed should fix this.

ipdb and pytest were only installed as dev dependencies- they are global now. importlib_resources and importlib_metadata are installed with pytest.
the db directory was untracked- it should be available now.

I'm a little confused on the revisions/upgrades- they should exist if you run `alembic upgrade head` in the intro. This one is definitely a little tricky, since I'm not seeing these issues locally. I might recruit Prabhdip to take a second look.

**Comment by professor-ben** [comment]
added .13 to the python version- this seems to fix the importlib issue. i'm closing this for now, but it will stay in the back of my mind (possibly forever)

-Ben
